### ISSUE TITLE
Histograph input file format

### ISSUE THREAD

**Issue by bertspaan** [histograph/io#1]
First DRAFT: https://gist.github.com/bertspaan/b8fad68e45543a5dcf51

@reinvantveer all datasets in [`historische-geocoder`](https://github.com/erfgoed-en-locatie/historische-geocoder/tree/gh-pages/data) repository should be converted to this new input format for datasets.
- [x] bag
- [x] dbpedia
- [x] gemeentegeschiedenis
- [x] geonames
- [ ] graafschappen
- [x] ilvb
- [x] militieregisters
- [x] nationaal wegenbestand
- [x] pleiades
- [x] poorterboeken
- [x] simon hart
- [ ] straten
- [x] tgn
- [x] verdwenen dorpen
- [x] voc-opvarenden

**Comment by reinvantveer** [comment]
Nationaal wegenbestand has an attribute "gme_id" converted to Integer cbs_code, representing the same cbs_code as mentioned in gemeentegeschiedenis. Inference rule should be implemented.

**Comment by reinvantveer** [comment]
No internal relational mapping within gemeentegeschiedenis data set has been made. Inferencing or new source data mappings have to be made. Only links from gemeentegeschiedenis to geonames have been mapped.

**Comment by reinvantveer** [comment]
Nationaal wegenbestand has no mapping to places. This should be inferred based on closest hg:Place

**Comment by reinvantveer** [comment]
There are no relational mappings for TGN yet. Inference rules should be constructed.

**Comment by reinvantveer** [comment]
TGN ontology for place types have been "dumbed down" to one of four types: hg:Area, hg:Place, hg:Water or hg:Object

**Comment by reinvantveer** [comment]
Verdwenen dorpen data set has no edges yet. Inference rules should be constructed.

**Comment by reinvantveer** [comment]
Done for all datasets except graafschappen and straten from monuments.
