### ISSUE TITLE
IO rejects edges between existing data sets

### ISSUE THREAD

**Issue by reinvantveer** [histograph/io#11]
Somehow, at the moment IO does not accept new edges between already existing data sets, or between newly added nodes and existing nodes.

**Comment by rutgervanwilligen** [comment]
Ha Rein, heb je een concreet voorbeeld? Ik snap niet direct wat er precies misgaat.

**Comment by reinvantveer** [comment]
Euh, bijvoorbeeld genoemd bij https://github.com/erfgoed-en-locatie/historische-geocoder/issues/57

**Comment by reinvantveer** [comment]
Wordt er een log gemaakt van edges die geweigerd worden? Of is het zinvol om gewoon eens de hele graaf leeg te mikken en opnieuw te vullen? Hoe doe ik dat?

**Comment by bertspaan** [comment]
Core gaat nog niet goed om met geweigerde edges. Dat moeten we aan 't eind van deze sprint, of in de volgende sprint maken (samen met _reasoning engine_). Graaf wegmikken kan:

```
rm -rf /tmp/histograph
```

(of een andere directory, hangt van je configuratiebestand `histograph.json` af.)

**Comment by rutgervanwilligen** [comment]
Denk dat dat nu fixed is. Reopenen mag als ik weg ben ;)
