### ISSUE TITLE
hg:isUsedFor relations are changed to hg:sameHgConcept relations

### ISSUE THREAD

**Issue by mmmenno** [histograph/io#16]
After completely deleting source Poorterboeken and importing everything again this still happens. Check [https://api.histograph.io/search?hgid=tgn/1047707](https://api.histograph.io/search?hgid=tgn/1047707) and you'll find only sameHgConcept relations with poorterboeken, whereas relations.ndjson reads like:

``` json
{"from":"526","to":"http://vocab.getty.edu/tgn/1047707","label":"hg:isUsedFor"}
{"from":"527","to":"http://vocab.getty.edu/tgn/1047707","label":"hg:isUsedFor"}
{"from":"532","to":"http://vocab.getty.edu/tgn/1048287","label":"hg:isUsedFor"}
{"from":"533","to":"http://vocab.getty.edu/tgn/1048161","label":"hg:isUsedFor"}
{"from":"534","to":"http://vocab.getty.edu/tgn/1048205","label":"hg:isUsedFor"}
```

**Comment by bertspaan** [comment]
Related: histograph/schemas#10.
