### ISSUE TITLE
Rename source > dataset

### ISSUE THREAD

**Issue by bertspaan** [histograph/io#19]
Do it.

**Comment by wires** [comment]
also add it to schema
https://github.com/histograph/schemas/blob/graphmalizer/json/pits.schema.json
?

**Comment by bertspaan** [comment]
PIT NDJSON files do not need to specify their dataset - that happens their `:dataset.dataset.json`: https://github.com/histograph/schemas/blob/graphmalizer/json/dataset.schema.json 😩

PIT NDJSON files are only valid within a single dataset context!
